name: Infracost

on:
  workflow_call:
    secrets:
      INFRACOST_API_KEY:
        required: true
        description: Infracost API KEY of organization

jobs:
  # This stage runs the Infracost CLI and posts PR comments.
  # It also updates PR comments when the PR is updated (synchronize event).
  infracost-pull-request-checks:
    name: Infracost Pull Request Checks
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:

      - name: Setup Infracost
        uses: infracost/actions/setup@v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost JSON
        run: |
          infracost breakdown --path /code --format json --out-file /tmp/infracost.json
      
      - name: Post Infracost comment
        run: |
            infracost comment github --path=/tmp/infracost.json \
              --repo=${{ github.repository }} \
              --github-token=${{ github.token }} \
              --pull-request=${{ github.event.pull_request.number }} \
              --behavior=update
