name: Semantic Release

on:
  workflow_call:
    outputs:
      release_version: 
        description: 'The version of the release'
        value: ${{ jobs.semantic-release.outputs.release_version }}
      release_major_version:
        description: 'The major version of the release'
        value: ${{ jobs.semantic-release.outputs.release_major_version }}
      release_minor_version:
        description: 'The minor version of the release'
        value: ${{ jobs.semantic-release.outputs.release_minor_version }}
      release_patch_version:
        description: 'The patch version of the release'
        value: ${{ jobs.semantic-release.outputs.release_patch_version }}
      pre_release_version: 
        description: 'The version of the release'
        value: ${{ jobs.semantic-release.outputs.release_version }}

jobs:
  semantic-release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Prepare prerelease semantic
        if: github.ref == 'refs/heads/develop'
        run: mv .releaserc.prerelease.yaml .releaserc.yaml
        
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 17
          extra_plugins: |
            @semantic-release/changelog@5
            @semantic-release/exec@5
            @semantic-release/git@9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Show Release Info
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          VERSION=${{ steps.semantic.outputs.new_release_version }}
          echo "Resolved version: $VERSION"
          echo "release_version=$VERSION" >> $GITHUB_OUTPUT
