name: Semantic Release

on:
  workflow_call:
    inputs:
      pre_release:
        default: false
        type: string
        required: false
    outputs:
      release_version: 
        description: 'The version of the release'
        value: ${{ jobs.semantic-release.outputs.release_version }}
      release_major_version:
        description: 'The major version of the release'
        value: ${{ jobs.semantic-release.outputs.release_major_version }}
      release_minor_version:
        description: 'The minor version of the release'
        value: ${{ jobs.semantic-release.outputs.release_minor_version }}
      release_patch_version:
        description: 'The patch version of the release'
        value: ${{ jobs.semantic-release.outputs.release_patch_version }}
      pre_release_version: 
        description: 'The version of the release'
        value: ${{ jobs.semantic-release.outputs.release_version }}
jobs:
  semantic-release:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Prepare prerelease semantic
        if: github.ref != 'refs/heads/main'
        run: mv .releaserc.prerelease.yaml .releaserc.yaml
      
      - name: Preview semantic-release
        if: ${{ inputs.pre_release }} != false
        run: |
          unset GITHUB_ACTIONS && npx semantic-release --dry-run --no-ci
        
      - name: Semantic Release
        if: ${{ inputs.pre_release }} == false
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 17
          extra_plugins: |
            @semantic-release/changelog@5
            @semantic-release/exec@5
            @semantic-release/git@9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Do something when a new release published
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo "release_version=${{ steps.semantic.outputs.new_release_version }}" >> $GITHUB_OUTPUT
          echo "release_major_version=${{ steps.semantic.outputs.new_release_major_version }}" >> $GITHUB_OUTPUT
          echo "release_minor_version=${{ steps.semantic.outputs.new_release_minor_version }}" >> $GITHUB_OUTPUT
          echo "release_patch_version=${{ steps.semantic.outputs.new_release_patch_version }}" >> $GITHUB_OUTPUT
