name: Deploy App Tag Helm On Argo CD

on:
  workflow_call:
    inputs:
      new_tag:
        type: string
        required: true
        description: Repository Image Tag application to update on Helm Argo CD
      environment:
        type: string
        required: true
        description: Enviroment (prod, stg or dev) to set up ENV.yaml variables Helm
      project_name:
        type: string
        required: true
        description: Repository dir of the application Helm chart, that will be used to update tag on ENV.yaml

env:
  PROJECT_NAME: ${{ inputs.project_name }}
  ENVIRONMENT: ${{ inputs.environment }}
  NEW_TAG: ${{ inputs.new_tag }}

jobs:
  commit-argocd-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          repository: davidlimacardoso/gitops-apps-argocd
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          path: apps/helm/${{ env.PROJECT_NAME }}
      
      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@davidlimacardoso.com"
          git config --global user.name "github-actions[bot]"
          ls -la &&\
          sed -i "s/tag: .*/tag: ${{ env.NEW_TAG }}/" dev.yaml &&\
          cat dev.yaml &&\
          git add . &&\
          git commit -m "Update application image tag to $NEW_TAG" &&\
          git push origin/main
